name: 'Unit Test Backend'
description: 'Unit Test Backend'
inputs:
  codacy-token:
    description: "Codacy Token"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Get repository name"
      id: repo-name
      uses: MariachiBear/get-repo-name-action@v1.3.0
      with:
        with-owner: 'false'
    - name: "Test"
      shell: bash
      run: |
        task test:unit:ci
    - name: "Submit Coverage"
      shell: bash
      if: inputs.codacy-token != ''
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --api-token ${{ inputs.codacy-token }} --force-coverage-parser go -r bin/unit.cover.out
      env:
        CODACY_API_TOKEN: ${{ inputs.codacy-token }}
        CODACY_ORGANIZATION_PROVIDER: gh
        CODACY_USERNAME: azarc-io
        CODACY_PROJECT_NAME: ${{ steps.repo-name.outputs.repository-name }}
