name: 'Lint Backend'
description: 'Lint Backend'
inputs:
  token:
    description: "Github Token"
    required: true
  lint-version:
    description: "Golangci Lint Version"
    default: "v1.59.1"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: go.sum
        go-version-file: go.mod
    - name: "Fix git URL"
      shell: bash
      run: git config --global url."https://x-access-token:${{ inputs.token }}@github.com/".insteadOf "https://github.com/"
    - name: "Go Mod"
      shell: bash
      run: go mod download
    - name: "Lint"
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: ${{ inputs.lint-version }}
        skip-cache: true
