name: 'Build Go'
description: 'Build Go'
inputs:
  ghcr-token:
    description: "Github Registry Token"
    required: true
  issue:
    description: "Issue Number"
    required: true
  short-sha:
    description: "Short Commit SHA"
    required: true
  namespace:
    description: "K8S Namespace"
    required: true
  install-task:
    description: "Installation task name"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Create Docker Login Secret"
      shell: bash
      run: |
        kubectl create namespace ${{ inputs.namespace }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret docker-registry ghcr-login-secret \
          --docker-server="https://ghcr.io" \
          --docker-username="waeljammal" \
          --docker-password="${{ inputs.ghcr-token }}" \
          --docker-email="wael.jammal@azarc.io" \
          --namespace=${{ inputs.namespace }} \
          --dry-run=client -o yaml | kubectl apply -f -
    - name: "Deploy Dependency Charts"
      shell: bash
      run: task ci:install:dependency:charts
    - name: "Deploy Chart"
      shell: bash
      run: task ${{ inputs.install-task }}
      env:
        APP_IMAGE_TAG: ${{ inputs.issue }}-${{ github.run_number }}-${{ inputs.short-sha }}
        WEB_IMAGE_TAG: ${{ inputs.issue }}-${{ github.run_number }}-${{ inputs.short-sha }}
        NAMESPACE: ${{ inputs.namespace }}
