name: 'Lint Backend'
description: 'Lint Backend'
inputs:
  lint-version:
    description: "Golangci Lint Version"
    default: "v1.59.1"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Lint"
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: ${{ inputs.lint-version }}
        skip-cache: true
      env:
        GOPRIVATE: "github.com/azarc-io"
